### ISSUE TITLE
Introduce new Entity: Carrier

### ISSUE THREAD

**Issue by Sofiia2001** [vlad-bilyk/Bakery#18]
### Description
As a System User, I want to assign a carrier role to a person, so that they can be successfully stored as a carrier and added to Carrier Entity Centre. 

#### Implementation 
- [x] Create Master Entity/Companion object Manager using TG plugin

Carrier should have the following properties:
- [x] `person: Person`-  composite key member.
- [x] `desc: String` - read only, calculated.

### Expected outcome
Entity `Carrier` is introduced.  `Carrier`,  `CarrierCo` and  `CarrierDao` classes are configured.

**Comment by vlad-bilyk** [comment]
3 commits are not visible, because my memory is not the best.

**Comment by vlad-bilyk** [comment]
I forgot to add the dependency between employeeNo and carrier properties but I already fixed it in the next issue
