### ISSUE TITLE
Entity Master/Centre for Carrier

### ISSUE THREAD

**Issue by Sofiia2001** [vlad-bilyk/Bakery#19]
### Description
As a System User, I want to be able to use Carrier Entity Centre and Master, so that I can read and edit carriers' info.

#### Implementation
 
- [x] Create Simple Master/Centre for `Carrier` using TG plugin
- [x] Person Entity Master should be used in place of Carrier Entity Master
- [x] Carrier Entity Centre search criteria should be the same as in Person except for `isCarrier`

### Expected outcome
Ability to edit and retrieve information about Carrier. Ability to search through Carrier.

Depends on #18

**Comment by vlad-bilyk** [comment]
2 commits are not visible (sorry...)
