### ISSUE TITLE
Entity Master/Centre for OrderItem

### ISSUE THREAD

**Issue by NazarTodo** [vlad-bilyk/Bakery#21]
### Description
As a System User, I want to be able to use OrderItem Entity Centre and Master, so that I can read and edit info about orders' content.

#### Implementation

- [x] Create Simple Master/Centre for `OrderItem` using TG plugin
- [x] `OrderItem` Entity Centre search criteria should be: order, product

### Expected outcome
Ability to edit and retrieve information about `OrderItem`. Ability to search through OrderItem.

Depend on #20

**Comment by vlad-bilyk** [comment]
Please provide quantity as range and decimal in OrderItem Entity Centre search criteria.
