### ISSUE TITLE
Improving Order

### ISSUE THREAD

**Issue by vlad-bilyk** [vlad-bilyk/Bakery#32]
### Description
Time to improve `Order` Entity

#### Implementation
TODO:

- [x]  Re-do validator for same locations, to fix error with Edit of the `Order`

- [x] Add integrity constraints for properties

- [x] Change type of the property `carrier` from String to Carrier.

### Expected outcome
Entity `Order` is improved.

**Comment by NazarTodo** [comment]
Done!
