### ISSUE TITLE
Assigning manager role and manager to Person

### ISSUE THREAD

**Issue by vlad-bilyk** [vlad-bilyk/Bakery#6]
### Description
As a System User I want to be able to assign a manager role and a manager to a Person, so that the relationship between employees and their managers can be represented.

#### Implementation

`Person` should have two new following properties

- [x] `manager: Boolean` - cannot be set to true if `employeeNo` is empty. 

- [x] `aManager: Manager` - is required if `employeeNo` is not empty. If `manager` is true - not required. 

- [x] Person Entity Centre and Master needs to be improved to allow to search by these 2 properties and modify them.

### Expected outcome
Ability to assign a manager and a manager role to Person.

**Comment by sofiagarkot** [comment]
Great work! Everything works properly. The validators and definers are determined. The search by 2 properties is performed correctly.
